package gui;

import database.Database;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.Arrays;


/**
 *
 * @author Footdua
 */
public class MahasiswaInterface extends javax.swing.JFrame {
    final Database database;
    private String roleChecker;
    CardLayout cardLayout;
    /**
     * Creates new form MahasiswaInterface
     */
    public MahasiswaInterface(String roleChecker) {
        initComponents();
        database = new Database();
        this.roleChecker = roleChecker;
        pnlCards.add(suratPanel, "pnlCard2");
        pnlCards.add(profilPanel, "pnlCard1");
        Navigation.setPreferredSize(new Dimension(49, 520)); 
        Navigation.setVisible(true);
        cardLayout = (CardLayout) (pnlCards.getLayout());

    }

    public MahasiswaInterface() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Navigation = new javax.swing.JPanel();
        profil = new javax.swing.JButton();
        surat = new javax.swing.JButton();
        orangePanel = new javax.swing.JPanel();
        navButton = new javax.swing.JButton();
        mahasiswaText = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        profilPanel = new javax.swing.JPanel();
        bioData1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        namaLengkap = new javax.swing.JLabel();
        nimNomor = new javax.swing.JLabel();
        programStudi = new javax.swing.JLabel();
        jenjangStudi = new javax.swing.JLabel();
        ipkMahasiswa = new javax.swing.JLabel();
        kontakNomor = new javax.swing.JLabel();
        angkatanTahun = new javax.swing.JLabel();
        semesterTahun = new javax.swing.JLabel();
        alamatRumah = new javax.swing.JLabel();
        tempatTanggalLahir = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        changeButton = new javax.swing.JButton();
        suratPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(204, 204, 204));
        background.setMaximumSize(new java.awt.Dimension(960, 578));
        background.setPreferredSize(new java.awt.Dimension(960, 578));

        Navigation.setBackground(new java.awt.Color(204, 204, 204));
        Navigation.setMaximumSize(new java.awt.Dimension(110, 520));
        Navigation.setMinimumSize(new java.awt.Dimension(60, 520));
        Navigation.setName(""); // NOI18N
        Navigation.setPreferredSize(new java.awt.Dimension(60, 520));
        Navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profil.setBackground(new java.awt.Color(51, 51, 51));
        profil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profil.setForeground(new java.awt.Color(51, 51, 51));
        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profilIcon.png"))); // NOI18N
        profil.setText("Profil");
        profil.setBorderPainted(false);
        profil.setContentAreaFilled(false);
        profil.setIconTextGap(15);
        profil.setInheritsPopupMenu(true);
        profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilActionPerformed(evt);
            }
        });
        Navigation.add(profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 140, -1));

        surat.setBackground(new java.awt.Color(51, 51, 51));
        surat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        surat.setForeground(new java.awt.Color(51, 51, 51));
        surat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/messageIcon.png"))); // NOI18N
        surat.setText("Surat");
        surat.setBorderPainted(false);
        surat.setContentAreaFilled(false);
        surat.setIconTextGap(16);
        surat.setInheritsPopupMenu(true);
        surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suratActionPerformed(evt);
            }
        });
        Navigation.add(surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 40, 140, -1));

        orangePanel.setBackground(new java.awt.Color(255, 153, 51));
        orangePanel.setMaximumSize(new java.awt.Dimension(970, 60));
        orangePanel.setName(""); // NOI18N

        navButton.setBackground(new java.awt.Color(255, 153, 51));
        navButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ButtonIcon.png"))); // NOI18N
        navButton.setContentAreaFilled(false);
        navButton.setDoubleBuffered(true);
        navButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navButtonActionPerformed(evt);
            }
        });

        mahasiswaText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mahasiswaText.setForeground(new java.awt.Color(255, 255, 255));
        mahasiswaText.setText("MAHASISWA");

        javax.swing.GroupLayout orangePanelLayout = new javax.swing.GroupLayout(orangePanel);
        orangePanel.setLayout(orangePanelLayout);
        orangePanelLayout.setHorizontalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mahasiswaText)
                .addContainerGap(754, Short.MAX_VALUE))
        );
        orangePanelLayout.setVerticalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addComponent(mahasiswaText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(navButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlCards.setBackground(new java.awt.Color(255, 255, 255));
        pnlCards.setLayout(new java.awt.CardLayout());

        profilPanel.setBackground(new java.awt.Color(204, 204, 204));
        profilPanel.setMaximumSize(new java.awt.Dimension(1000, 1000));
        profilPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        profilPanel.setName(""); // NOI18N
        profilPanel.setPreferredSize(new java.awt.Dimension(960, 578));
        profilPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bioData1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 166, 90));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 166, 90));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 9)); // NOI18N
        jLabel2.setText("Anda perlu memperbarui data diri Anda secara berkala karena data ini akan digunakan sebagai referensi dalam surat yang akan diajukan ke Fakultas Teknik Universitas Mulawarman.");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 30));

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nama Lengkap");

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nim");

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Program Studi");

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Jenjang Studi");

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("IPK");

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Kontak");

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Angkatan");

        jLabel21.setBackground(new java.awt.Color(51, 51, 51));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Semester");

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Alamat");

        jLabel23.setBackground(new java.awt.Color(51, 51, 51));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Tempat Tanggal Lahir");

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(":");

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText(":");

        jLabel27.setBackground(new java.awt.Color(51, 51, 51));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(":");

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText(":");

        jLabel29.setBackground(new java.awt.Color(51, 51, 51));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText(":");

        jLabel30.setBackground(new java.awt.Color(51, 51, 51));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText(":");

        jLabel31.setBackground(new java.awt.Color(51, 51, 51));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText(":");

        jLabel32.setBackground(new java.awt.Color(51, 51, 51));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText(":");

        jLabel33.setBackground(new java.awt.Color(51, 51, 51));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText(":");

        jLabel34.setBackground(new java.awt.Color(51, 51, 51));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText(":");

        namaLengkap.setBackground(new java.awt.Color(51, 51, 51));
        namaLengkap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaLengkap.setForeground(new java.awt.Color(51, 51, 51));
        namaLengkap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLengkap.setText("Nama Lengkap");
        namaLengkap.setToolTipText("");
        namaLengkap.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        nimNomor.setBackground(new java.awt.Color(51, 51, 51));
        nimNomor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nimNomor.setForeground(new java.awt.Color(51, 51, 51));
        nimNomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nimNomor.setText("Nim");
        nimNomor.setToolTipText("");
        nimNomor.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        programStudi.setBackground(new java.awt.Color(51, 51, 51));
        programStudi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        programStudi.setForeground(new java.awt.Color(51, 51, 51));
        programStudi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programStudi.setText("Program Studi");
        programStudi.setToolTipText("");
        programStudi.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jenjangStudi.setBackground(new java.awt.Color(51, 51, 51));
        jenjangStudi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jenjangStudi.setForeground(new java.awt.Color(51, 51, 51));
        jenjangStudi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jenjangStudi.setText("Jenjang Studi");
        jenjangStudi.setToolTipText("");
        jenjangStudi.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ipkMahasiswa.setBackground(new java.awt.Color(51, 51, 51));
        ipkMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ipkMahasiswa.setForeground(new java.awt.Color(51, 51, 51));
        ipkMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ipkMahasiswa.setText("IPK");
        ipkMahasiswa.setToolTipText("");
        ipkMahasiswa.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        kontakNomor.setBackground(new java.awt.Color(51, 51, 51));
        kontakNomor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kontakNomor.setForeground(new java.awt.Color(51, 51, 51));
        kontakNomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kontakNomor.setText("Kontak");
        kontakNomor.setToolTipText("");
        kontakNomor.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        angkatanTahun.setBackground(new java.awt.Color(51, 51, 51));
        angkatanTahun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        angkatanTahun.setForeground(new java.awt.Color(51, 51, 51));
        angkatanTahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        angkatanTahun.setText("Angkatan");
        angkatanTahun.setToolTipText("");
        angkatanTahun.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        semesterTahun.setBackground(new java.awt.Color(51, 51, 51));
        semesterTahun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        semesterTahun.setForeground(new java.awt.Color(51, 51, 51));
        semesterTahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semesterTahun.setText("Semester");
        semesterTahun.setToolTipText("");
        semesterTahun.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        alamatRumah.setBackground(new java.awt.Color(51, 51, 51));
        alamatRumah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alamatRumah.setForeground(new java.awt.Color(51, 51, 51));
        alamatRumah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamatRumah.setText("Alamat");
        alamatRumah.setToolTipText("");
        alamatRumah.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tempatTanggalLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tempatTanggalLahir.setForeground(new java.awt.Color(51, 51, 51));
        tempatTanggalLahir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tempatTanggalLahir.setText("Tempat Tanggal Lahir");
        tempatTanggalLahir.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Data Diri Mahasiswa");

        changeButton.setBackground(new java.awt.Color(255, 153, 51));
        changeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changeButton.setForeground(new java.awt.Color(255, 255, 255));
        changeButton.setText("Ubah Data");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bioData1Layout = new javax.swing.GroupLayout(bioData1);
        bioData1.setLayout(bioData1Layout);
        bioData1Layout.setHorizontalGroup(
            bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bioData1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bioData1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bioData1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel30)
                                .addGap(27, 27, 27)
                                .addComponent(kontakNomor))
                            .addGroup(bioData1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel31)
                                .addGap(27, 27, 27)
                                .addComponent(angkatanTahun))
                            .addGroup(bioData1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel32)
                                .addGap(27, 27, 27)
                                .addComponent(semesterTahun))
                            .addGroup(bioData1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel33)
                                .addGap(27, 27, 27)
                                .addComponent(alamatRumah))
                            .addGroup(bioData1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel34)
                                .addGap(27, 27, 27)
                                .addComponent(tempatTanggalLahir))
                            .addGroup(bioData1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bioData1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel27)
                                        .addGap(27, 27, 27)
                                        .addComponent(programStudi))
                                    .addGroup(bioData1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel28)
                                        .addGap(27, 27, 27)
                                        .addComponent(jenjangStudi))
                                    .addGroup(bioData1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(115, 115, 115)
                                        .addComponent(jLabel29)
                                        .addGap(27, 27, 27)
                                        .addComponent(ipkMahasiswa))
                                    .addGroup(bioData1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel25)
                                        .addGap(27, 27, 27)
                                        .addComponent(namaLengkap))
                                    .addGroup(bioData1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel26)
                                        .addGap(27, 27, 27)
                                        .addComponent(nimNomor)))))
                        .addGap(158, 158, 158))
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changeButton)
                            .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        bioData1Layout.setVerticalGroup(
            bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bioData1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(namaLengkap))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(nimNomor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(programStudi))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jenjangStudi))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(ipkMahasiswa))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(kontakNomor))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(angkatanTahun))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(semesterTahun))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(alamatRumah))))
                .addGap(12, 12, 12)
                .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addGroup(bioData1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bioData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(tempatTanggalLahir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(changeButton)
                .addGap(16, 16, 16))
        );

        profilPanel.add(bioData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 870, 480));

        pnlCards.add(profilPanel, "card3");

        suratPanel.setBackground(new java.awt.Color(255, 255, 255));
        suratPanel.setMaximumSize(new java.awt.Dimension(960, 578));
        suratPanel.setMinimumSize(new java.awt.Dimension(960, 578));
        suratPanel.setName(""); // NOI18N
        suratPanel.setPreferredSize(new java.awt.Dimension(960, 578));
        suratPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlCards.add(suratPanel, "card2");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(orangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCards, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard1");
        String nimToCheck = roleChecker;
        String[] data = (String[]) database.retrieveData(nimToCheck);

        if (data != null) {
            System.out.println("NIM: " + Arrays.toString(data));
            namaLengkap.setText((String) data[0]);
            nimNomor.setText((String) data[1]);
            programStudi.setText((String) data[2]);
            jenjangStudi.setText((String) data[3]);
            ipkMahasiswa.setText((String) data[4]);
            kontakNomor.setText((String) data[5]);
            angkatanTahun.setText((String) data[6]);
            semesterTahun.setText((String) data[7]);
            alamatRumah.setText((String) data[8]);
            tempatTanggalLahir.setText((String) data[9]);
        } else {
            System.out.println("Data tidak ditemukan");
        }
    }//GEN-LAST:event_profilActionPerformed

    private void suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suratActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard2");
    }//GEN-LAST:event_suratActionPerformed

    private void navButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navButtonActionPerformed
        // TODO add your handling code here:
        if  (Navigation.getSize().equals(new Dimension(49, 520))){
            Navigation.setPreferredSize(new Dimension(110, 520));
        } else {
            Navigation.setPreferredSize(new Dimension(49, 520));
        }
        Navigation.revalidate();
        Navigation.repaint();
    }//GEN-LAST:event_navButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MahasiswaInterface("roleChecker").setVisible(true);
            MahasiswaInterface mahasiswaInterface = new MahasiswaInterface("roleChecker");
            mahasiswaInterface.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navigation;
    private javax.swing.JLabel alamatRumah;
    private javax.swing.JLabel angkatanTahun;
    private javax.swing.JPanel background;
    private javax.swing.JPanel bioData1;
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel ipkMahasiswa;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jenjangStudi;
    private javax.swing.JLabel kontakNomor;
    private javax.swing.JLabel mahasiswaText;
    private javax.swing.JLabel namaLengkap;
    private javax.swing.JButton navButton;
    private javax.swing.JLabel nimNomor;
    private javax.swing.JPanel orangePanel;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JButton profil;
    private javax.swing.JPanel profilPanel;
    private javax.swing.JLabel programStudi;
    private javax.swing.JLabel semesterTahun;
    private javax.swing.JButton surat;
    private javax.swing.JPanel suratPanel;
    private javax.swing.JLabel tempatTanggalLahir;
    // End of variables declaration//GEN-END:variables

    private void retrieveUserData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
